### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by adxhyt** [jmxtrans/jmxtrans#374] opened 2015-12-14 11:28 UTC
when i try to run ./jmxtrans.sh start.  it gets errors like this:

[work@mac jmxtrans]$ ./jmxtrans.sh start /var/lib/jmxtrans/test_out.json
.
[work@mac jmxtrans]$
java.lang.UnsatisfiedLinkError: /home/work/log/jpathwatch-nativelib-v-0-95-libjpathwatch-native.so: libstdc++.so.6: cannot open shared object file: No such file or directory
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1086)
    at name.pachler.nio.file.impl.NativeLibLoader.extractAndLoadLibrary(NativeLibLoader.java:407)
    at name.pachler.nio.file.impl.NativeLibLoader.loadLibrary(NativeLibLoader.java:257)
    at name.pachler.nio.file.impl.LinuxPathWatchService.<clinit>(LinuxPathWatchService.java:105)
    at name.pachler.nio.file.ext.Bootstrapper.newWatchService(Bootstrapper.java:80)
    at name.pachler.nio.file.FileSystems$1.newWatchService(FileSystems.java:40)
    at com.googlecode.jmxtrans.util.WatchDir.<init>(WatchDir.java:33)
    at com.googlecode.jmxtrans.JmxTransformer.startupWatchdir(JmxTransformer.java:259)
    at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:138)
    at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:107)
    at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:92)
java.lang.UnsatisfiedLinkError: no jpathwatch-native in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at name.pachler.nio.file.impl.NativeLibLoader.loadDefaultLibrary(NativeLibLoader.java:84)
    at name.pachler.nio.file.impl.NativeLibLoader.loadLibrary(NativeLibLoader.java:277)
    at name.pachler.nio.file.impl.LinuxPathWatchService.<clinit>(LinuxPathWatchService.java:105)
    at name.pachler.nio.file.ext.Bootstrapper.newWatchService(Bootstrapper.java:80)
    at name.pachler.nio.file.FileSystems$1.newWatchService(FileSystems.java:40)
    at com.googlecode.jmxtrans.util.WatchDir.<init>(WatchDir.java:33)
    at com.googlecode.jmxtrans.JmxTransformer.startupWatchdir(JmxTransformer.java:259)
    at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:138)
    at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:107)
    at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:92)

# configuration file for package jmxtrans
export JAVA_HOME="/home/work/jdk1.8.0_65"
export JAR_FILE="/usr/share/jmxtrans/jmxtrans-all.jar"
export LOG_DIR="/home/work/log/jmxtrans"
export SECONDS_BETWEEN_RUNS=60
export JSON_DIR="/var/lib/jmxtrans"

I read the previous questions and changed JMXTRANS_OPTS, but the error still exists:

now the path /home/work/log is:

ll /home/work  drwxrwxr-x  2 work work      4096 Dec 14 18:29 log

JMXTRANS_OPTS="$JMXTRANS_OPTS -Djmxtrans.log.level=${LOG_LEVEL} -Djmxtrans.log.dir=$LOG_DIR -Djava.io.tmpdir=/home/work/log"

how can i fix this error?

**Comment by gehel** [comment] 2015-12-14 13:05
My first guess would be that there is some incompatibility between jpathwatch and the version of MacOS that you are using. Could you checkout the code and try to run the related integration test (https://github.com/jmxtrans/jmxtrans/blob/master/jmxtrans-utils/src/test/java/com/googlecode/jmxtrans/util/WatchDirTest.java) ?

**Comment by adxhyt** [comment] 2015-12-14 14:43
thx a lot. Solved the problem. check the env and compile a newer version gcc. It seems that the program can't find libstdc++.so.6, which is what jpathwatch's native library is linked against.

**Comment by gehel** [comment] 2015-12-16 12:11
As I understand, the issue is solved, so I'm closing it. Feel free to re-open if that's not the case.

**Closed by gehel** 2015-12-16 12:11 UTC
