### ISSUE TITLE
Issue related to configuration of influxdb with jmxtrans 

### ISSUE THREAD

**Issue by akhan4u** [jmxtrans/jmxtrans#574] opened 2017-06-19 12:11 UTC
Hi i am getting the below error while setting up influxbd with jmxtrans for monitoring data from kafka 

```
[19 Jun 2017 17:39:53] [jmxtrans-result-7] 256568 WARN  (com.googlecode.jmxtrans.jmx.ResultProcessor$1:60) - Could not write results [Result(attributeName=HeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, values={init=1073741824, committed=1073741824, max=1073741824, used=510296072}, epoch=1497874193415, keyAlias=jvmMemory), Result(attributeName=NonHeapMemoryUsage, className=sun.management.MemoryImpl, objDomain=java.lang, typeName=type=Memory, values={init=2555904, committed=53870592, max=-1, used=52743976}, epoch=1497874193415, keyAlias=jvmMemory)] of query Query(objectName=java.lang:type=Memory, keys=[], attr=[HeapMemoryUsage, NonHeapMemoryUsage], typeNames=[], resultAlias=jvmMemory, useObjDomainAsKey=false, allowDottedKeys=false, useAllTypeNames=false, outputWriterInstances=[com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@4dc41b51]) to output writer com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter@4dc41b51
java.lang.RuntimeException: {"error":"error parsing query: found NOT, expected ; at line 1, char 20"}

        at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
        at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
        at org.influxdb.impl.$Proxy29.query(Unknown Source)
        at org.influxdb.impl.InfluxDBImpl.createDatabase(InfluxDBImpl.java:205)
        at com.googlecode.jmxtrans.model.output.InfluxDbWriter.doWrite(InfluxDbWriter.java:151)
        at com.googlecode.jmxtrans.model.output.support.ResultTransformerOutputWriter.doWrite(ResultTransformerOutputWriter.java:50)
        at com.googlecode.jmxtrans.jmx.ResultProcessor$1.run(ResultProcessor.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by gehel** [comment] 2017-06-19 12:15
@akhan4u which versino of jmxtrans are you using?

**Comment by akhan4u** [comment] 2017-06-20 04:53
I am using Jmxtrans version : 259 
`[root@localhost ~]# rpm -qa | grep jmx
jmxtrans-259-1.noarch
[root@localhost ~]# rpm -qi jmxtrans
Name        : jmxtrans                     Relocations: (not relocatable)
Version     : 259                               Vendor: JmxTrans team
Release     : 1                             Build Date: Wednesday 06 July 2016 09:51:44 PM IST
Install Date: Monday 19 June 2017 03:24:41 PM IST      Build Host: testing-gce-5a223b66-a9b4-4ed0-b203-53fbfbc6d237.c.travis-ci-prod-5.internal
Group       : Applications/Communications   Source RPM: jmxtrans-259-1.src.rpm
Size        : 35054808                         License: (c) 2010 JmxTrans team
Signature   : (none)
Packager    : JmxTrans team
URL         : https://github.com/jmxtrans/
Summary     : JmxTrans
Description :
JMX metrics exporter.

		This module creates the packaging for JmxTrans. It does not contain any application code, but creates .deb, .rpm
		or other packaging.
[root@localhost ~]# 
`

**Comment by akhan4u** [comment] 2017-06-20 04:54
i am using Jmxtrans 259... 

[root@localhost ~]# rpm -qa | grep jmx
jmxtrans-259-1.noarch
[root@localhost ~]# rpm -qi jmxtrans
Name        : jmxtrans                     Relocations: (not relocatable)
Version     : 259                               Vendor: JmxTrans team
Release     : 1                             Build Date: Wednesday 06 July 2016 09:51:44 PM IST
Install Date: Monday 19 June 2017 03:24:41 PM IST      Build Host: testing-gce-5a223b66-a9b4-4ed0-b203-53fbfbc6d237.c.travis-ci-prod-5.internal
Group       : Applications/Communications   Source RPM: jmxtrans-259-1.src.rpm
Size        : 35054808                         License: (c) 2010 JmxTrans team
Signature   : (none)
Packager    : JmxTrans team
URL         : https://github.com/jmxtrans/
Summary     : JmxTrans
Description :
JMX metrics exporter.

		This module creates the packaging for JmxTrans. It does not contain any application code, but creates .deb, .rpm
		or other packaging.
[root@localhost ~]#

**Comment by gehel** [comment] 2017-06-20 07:34
Latest version is 265 (available on [Maven central](http://central.maven.org/maven2/org/jmxtrans/jmxtrans/265/)). Could you upgrade and see if you still have the issue?

**Comment by akhan4u** [comment] 2017-06-20 09:00
sure i will do and update... and let you know! thanks

**Comment by 4nky-mnky** [comment] 2017-10-15 00:31
can confirm the issue is resolved in the v265 of jmxtrans.

**Comment by gehel** [comment] 2017-10-15 11:33
@4nky-mnky thanks for the report!

**Closed** 2017-10-15 11:33 UTC
