### ISSUE TITLE
jmxtrans frezy with ~5000 metrics

### ISSUE THREAD

**Issue by tbarbugli** [jmxtrans/jmxtrans#384] opened 2015-12-24 14:37 UTC
I am using build 256 with 2 threads and graphite as output (GraphiteWriterFactory) to collect ~5000 JMX metrics from Cassandra. I started with collecting only a few hundreds and I saw that as the metric count was going up there was an increase in missing data. When I tried with ~5000 not a single metric was reaching graphite, at that moment I saw that jmxtrans had hundreds of threads and was using 100% CPU.

Here's the thread dump: https://gist.github.com/tbarbugli/b378fc9ec0f661fb0d6d

here's the configuration I am using:

```
export LOG_DIR="/var/log/jmxtrans"
export LOG_FILE="/var/log/jmxtrans/jmxtrans.log"
export SECONDS_BETWEEN_RUNS=60
export JSON_DIR="/var/lib/jmxtrans"
export HEAP_SIZE=512
export LOG_LEVEL=warn
export JAR_FILE=/usr/share/jmxtrans/lib/jmxtrans-all.jar
```

The json query config has 468 queries, each with the same outputwriters section (so my guess is that 1 thread is created for each query even if the writer has the same settings). Is there a way to define a "global" outputwriter or to limit the amount of outputwriters' threads?

**Comment by gehel** [comment] 2015-12-25 21:14
The thread dump looks a lot like insufficient testing and ugly bug on my side. I'm a bit puzzled as to where you found a version 256 of jmxtrans. The latest release is 2.5.3...

**Comment by gehel** [comment] 2015-12-26 08:19
#385 introduces OutputWriters on Server, which should solve your issue.

**Comment by tbarbugli** [comment] 2015-12-26 08:33
I meant build 253 sorry. I am going to give #385 a try today and let you know ;)

**Comment by gehel** [comment] 2015-12-26 21:39
#385 has been merged and should be available in latest snapshot. I did not update documentation, but in short, there is a new `outputWriters` attribute in servers that follow the same syntax and semantic as its counterpart in queries. There is also no tests of this new functionality, so use it at your own risk.

I'd be interested in having a look at your json config fiel if you could send it...

**Comment by tbarbugli** [comment] 2015-12-27 17:49
can't find the snapshot for 254, do you store that somewhere else than in MC?

**Comment by gehel** [comment] 2015-12-27 18:04
Yep, Snapshots are hosted on [Sonatype snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/org/jmxtrans/jmxtrans/)

**Comment by tbarbugli** [comment] 2015-12-27 18:26
tried 254 snapshot now but if I remove outputWriters from queries and add one in the server the config parsing fails. I had a look at the code and I was wondering if this is because outputWriters is a required field for queries objects. Jackson error log is pretty much useless (java.lang.NullPointerException kind of error) but I can add that if you need it

**Comment by gehel** [comment] 2015-12-27 18:34
Right, I did add the ability to configure OutputWriters at the server level, but did not remove the check at the Query level. I'll update that right away...

**Comment by gehel** [comment] 2015-12-27 18:37
I will merge #386 as soon as travis build is done.

**Comment by tbarbugli** [comment] 2015-12-28 08:03
I pulled the latest snapshot but I still get the same error, is the new code now there?


here's a simplified version of my json config
```json

    "servers": [
        {
            "host": "redacted",
            "numQueryThreads": 2,
            "outputWriters": [
                {
                    "@class": "com.googlecode.jmxtrans.model.output.GraphiteWriterFactory",
                    "host": "redacted",
                    "port": "2003",
                    "rootPrefix": "cassandra.jmx"
                }
            ],
            "port": "7199",
            "queries": [
                {
                    "attr": [
                        "CollectionCount",
                        "CollectionTime"
                    ],
                    "obj": "java.lang:type=GarbageCollector,name=*",
                    "resultAlias": "gc"
                },
                {
                    "attr": [
                        "HeapMemoryUsage",
                        "NonHeapMemoryUsage"
                    ],
                    "obj": "java.lang:type=Memory",
                    "resultAlias": "heap"
                },
                {
                    "attr": [
                        "ActiveCount",
                        "CompletedTasks",
                        "CurrentlyBlockedTasks",
                        "PendingTasks",
                        "TotalBlockedTasks"
                    ],
                    "obj": "org.apache.cassandra.internal:type=MemtablePostFlusher",
                    "resultAlias": "Internal/MemtablePostFlusher"
                },
                {
                    "attr": [
                        "ActiveCount",
                        "CompletedTasks",
                        "CurrentlyBlockedTasks",
                        "PendingTasks",
                        "TotalBlockedTasks"
                    ],
                    "obj": "org.apache.cassandra.internal:type=HintedHandoff",
                    "resultAlias": "Internal/HintedHandoff"
                },
                {
                    "attr": [
                        "RecentTotalTimouts",
                        "TotalTimeouts"
                    ],
                    "obj": "org.apache.cassandra.net:type=MessagingService",
                    "resultAlias": "MessagingService"
                },
                {
                    "attr": [
                        "PendingTasks",
                        "CompletedTasks"
                    ],
                    "obj": "org.apache.cassandra.db:type=CompactionManager",
                    "resultAlias": "CompactionManager"
                }
            ]
        }

```

and here the tail of /var/log/jmxtrans/jmxtrans.log

```
Caused by: java.lang.NullPointerException
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:239)
	at com.googlecode.jmxtrans.model.Query.<init>(Query.java:144)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:125)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:227)
	... 30 more

	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:461)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:376)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
[28 Dec 2015 07:58:33] [main] 1      ERROR (com.googlecode.jmxtrans.JmxTransformer:161) - Error parsing json: /var/lib/jmxtrans/cassandra.json
com.googlecode.jmxtrans.exceptions.LifecycleException: Error parsing json: /var/lib/jmxtrans/cassandra.json
	at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:58)
	at com.googlecode.jmxtrans.JmxTransformer.processFilesIntoServers(JmxTransformer.java:323)
	at com.googlecode.jmxtrans.JmxTransformer.startupSystem(JmxTransformer.java:291)
	at com.googlecode.jmxtrans.JmxTransformer.start(JmxTransformer.java:158)
	at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:130)
	at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:118)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.googlecode.jmxtrans.model.Query] value failed: null (through reference chain: com.googlecode.jmxtrans.model.JmxProcess["servers"]->java.util.ArrayList[0]->com.googlecode.jmxtrans.model.Server["queries"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:399)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:231)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:135)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:440)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:461)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:376)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3731)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2618)
	at com.googlecode.jmxtrans.util.JsonUtils.getJmxProcess(JsonUtils.java:44)
	at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:47)
	... 5 more
Caused by: java.lang.NullPointerException
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:239)
	at com.googlecode.jmxtrans.model.Query.<init>(Query.java:144)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:125)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:227)
	... 30 more
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3731)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2618)
	at com.googlecode.jmxtrans.util.JsonUtils.getJmxProcess(JsonUtils.java:44)
	at com.googlecode.jmxtrans.ConfigurationParser.parseServers(ConfigurationParser.java:47)
	... 5 more
Caused by: java.lang.NullPointerException
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:239)
	at com.googlecode.jmxtrans.model.Query.<init>(Query.java:144)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:125)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:227)
	... 30 more
```

**Comment by gehel** [comment] 2015-12-29 07:16
The code *should* be there. It is published automatically on each commit to master. Did you see that old snapshots are kept? There is at the moment 3 different snapshots of [254](https://oss.sonatype.org/content/repositories/snapshots/org/jmxtrans/jmxtrans/254-SNAPSHOT/).

**Comment by tbarbugli** [comment] 2015-12-29 08:22
the error happens on the last snapshot (254-20151227.190616-3)

**Comment by gehel** [comment] 2015-12-30 07:20
Damn, I see my mistake. Sorry for the delay...

Fix is on its way. It will include quite a few other changes, so as always, there is some risk that I broke something else.

By the way, the issue is with a `null` OutputWriter list. You should be able to work around it by defining an empty list of OutputWriters on the query:

    "queries": [
        {
            "attr": ["CollectionCount", "CollectionTime"],
            "obj": "java.lang:type=GarbageCollector,name=*",
            "resultAlias": "gc",
            "outputwriters": []
        }
    ]

**Comment by gehel** [comment] 2015-12-30 08:07
Feel free to reopen if it still does not work!

**Comment by tbarbugli** [comment] 2015-12-30 08:12
different error with the new snapshot

```
Exception in thread "main" javax.management.NotCompliantMBeanException: MBean class com.googlecode.jmxtrans.monitoring.ManagedThreadPoolExecutor does not implement DynamicMBean, and neither follows the Standard MBean conventions (javax.management.NotCompliantMBeanException: Class com.googlecode.jmxtrans.monitoring.ManagedThreadPoolExecutor is not a JMX compliant Standard MBean) nor the MXBean conventions (javax.management.NotCompliantMBeanException: com.googlecode.jmxtrans.monitoring.ManagedThreadPoolExecutor: Class com.googlecode.jmxtrans.monitoring.ManagedThreadPoolExecutor is not a JMX compliant MXBean)
	at com.sun.jmx.mbeanserver.Introspector.checkCompliance(Introspector.java:173)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:317)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at com.googlecode.jmxtrans.JmxTransformer.doMain(JmxTransformer.java:146)
	at com.googlecode.jmxtrans.JmxTransformer.main(JmxTransformer.java:133)
```

**Comment by gehel** [comment] 2015-12-30 08:14
Well, thanks for your patience! If you want to get something working fast, you should probably revert to 252. If you want to help me fix all the things I have broken lately, I'll be really happy!

**Comment by tbarbugli** [comment] 2015-12-30 08:17
glad to help with this, unfortunately I can't help much with Java but I can run some manual tests ;)

**Comment by tbarbugli** [comment] 2015-12-30 08:18
btw, doesn't 252 have the same issue when used with lot of queries? Does 252 reuses the same thread pool for all queries (graphite outputwriter)?

**Comment by gehel** [comment] 2015-12-30 08:23
If you use the old GraphiteWriter (and not the new GraphiteWriterFactory), you should be good.

Btw, the other issue should be fixed in a few minutes... Strange, it should have been caught by Integration tests.

**Comment by gehel** [comment] 2015-12-30 09:06
The previous GraphiteWriter is sharing a common thread pool for all TCP connections, so it is much more lightweight and does not cause issues if there are a lot of instances of the same writer. The new GraphiteWriter has a more subtle implementation, but I still need to ensure that I de-duplicate instances. This is going to be implemented quite soon, but I did release 253 a bit too soon. Sorry for the trouble.

**Comment by gehel** [comment] 2015-12-30 09:07
New snapshot should be published in a few minutes. You can keep an eye on the [Travis build](https://travis-ci.org/jmxtrans/jmxtrans/builds/99400429) to see when its completed.

**Comment by gehel** [comment] 2016-01-28 08:31
The latest snapshots should fix this issue. I'll close this for the moment. Feel free to re-open if needed.

**Closed by gehel** 2016-01-28 08:31 UTC
Labels: bug
